'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")>  _
Partial Friend NotInheritable Class ApplicationSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As ApplicationSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ApplicationSettings()),ApplicationSettings)
    
    Public Shared ReadOnly Property [Default]() As ApplicationSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""Provider=Microsoft.ACE.OLEDB.12.0;Data Source=F:\PurchasingDataDevelopment.mdb;P"& _ 
        "ersist Security Info=False;""")>  _
    Public ReadOnly Property ConnectionString() As String
        Get
            Return CType(Me("ConnectionString"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.07")>  _
    Public Property TaxRate() As Double
        Get
            Return CType(Me("TaxRate"),Double)
        End Get
        Set
            Me("TaxRate") = value
        End Set
    End Property
End Class
